### PR TITLE
Fixed issue #129, accessibility issue for add module to dashboard modal.

### PR DESCRIPTION
**Pull request by ahamed**
Pull Request for Issue #129, #128.

### Summary of Changes
This PR fixes accessibility issues of `Add module to the dashboard` modal. The following PR changes -

- Added `aria-label` attributes to the modal footer's `Close` and `Save & Close` buttons and remove unnecessary `aria-hidden` attributes from the buttons.
- Added `aria-labelledby` attribute on the module search input field.
- Added distinct `aria-label` for the **Select** module anchor tag.
- Added `title` attribute on the **modal's** `iframe`

### Testing Instructions
Go to `Dashboard` and scroll to the bottom of the page and click `Add modules to the dashboard` button.

### Expected result
The corresponding elements must have` aria-*` attributes.

### Actual result
No `aria-*` attributes found.

### CODE REVIEW

**Comment by brianteeman** [comment]
On the modal view the select link have a class
image

On the regular view (administrator/index.php?option=com_modules&view=select&client_id=1) the select links have no class
image

is that intentional?

**Comment by ahamed** [comment]
It's not intentional, it's a mistake. The class is added there conditionally we need to add the `class` attribute inside the condition. I will fix it here.

**Comment by brianteeman** [comment]
does what it says

**Comment by ahamed** [comment]
> does what it says

It's fixed.

**Comment by NguyenTrang091296** [comment]
I checked and I see aria-label has been updated for  all "Select". But Modules page, It still mistake class. 
image
image

**Comment by ahamed** [comment]
> But Modules page, It still mistake class.

The class is needed only for the modal view. So we remove it from the module view. It's intentional.

**Comment by NguyenTrang091296** [comment]
> > But Modules page, It still mistake class.
> 
> The class is needed only for the modal view. So we remove it from the module view. It's intentional.

Yes. Tks!

**Pull request merged**
