### PR TITLE
Fixed issue #130, Image copyright issue.

### PR DESCRIPTION
**Pull request by ahamed**
Pull Request for Issue #130 .

### Summary of Changes
Removed the previous dashboard module images and added new images that are completely free to use.

### Testing Instructions
Fetch the Pull Request and run the command on the terminal - 
`node build.js --copy-assets`

Then go to Dashboard and **Heard Reload** your browser.

### Before
Screenshot 2019-12-12 at 5 45 32 PM

### After
Screenshot 2019-12-12 at 5 44 17 PM

### CODE REVIEW

**Comment by brianteeman** [comment]
There are a lot of unrelated changes here

**Comment by brianteeman** [comment]
For the new language strings they should be inserted in alphabetical order with the other language strings and not appended to the end of the file

**Comment by kawshar** [comment]
> There are a lot of unrelated changes here

Not really. All are related.

**Comment by brianteeman** [comment]
@kawshar I corrected myself ;)

**Comment by ahamed** [comment]
> There are a lot of unrelated changes here

The image files are replaced and renamed so we needed to edit the actual image names as src of the images. And there are some language strings missing. So we add them. That's it.

> For the new language strings they should be inserted in alphabetical order with the other language strings and not appended to the end of the file

You are correct. We will fix this.

**Comment by kawshar** [comment]
> @kawshar I corrected myself ;)

Thank you 👍

**Comment by brianteeman** [comment]
@ahamed07sajeeb 
I corrected myself

**Comment by brianteeman** [comment]
Thanks for these images and addressing the copyright issue

**Comment by kawshar** [comment]
> Thanks for these images and addressing the copyright issue

Sorry for the trouble we caused.

**Comment by kawshar** [comment]
Screenshot 2019-12-13 at 3 29 26 PM
Issue resolved.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
