### PR TITLE
Fixed issue #50, Elements must have sufficient color contrast.

### PR DESCRIPTION
**Pull request by ahamed**
Pull Request for Issue #50. 

### Summary of Changes
These changes meet the contrast ratio threshold above 4.5:1.

### CODE REVIEW

**Comment by davidnguyen-joomlashine** [comment]
I checked the fix and the contrast ratio threshold is: 5.03:1
Screenshot (2)

As the expected result is 4.5:1 at here: #50, then you consider to use this value for "--icon-rgb": 110, 120, 129 (#6e7881)
Screenshot (3)

**Comment by ahamed** [comment]
The contrast ratio threshold is 4.5:1. If it exceeds 4.5 then it's not a problem I think as it satisfied the threshold value. Correct me if I am wrong.

**Comment by brianteeman** [comment]
You are correct

**Comment by davidnguyen-joomlashine** [comment]
Hi ahamed07sajeeb,

If so, I confirmed your fix is ok. 

Thank you

**Pull request merged**
