### PR TITLE
Fixed issue #83, Inconsistent status field in module form.

### PR DESCRIPTION
**Pull request by ahamed**
Pull Request for Issue #83.

### Summary of Changes
The input type changes from 'radio' to 'list' at `/administrator/components/com_modules/forms/module.xml`.

### Expected Result
The status should be the `select option` field.

### Actual Result
It shows radio buttons.

### CODE REVIEW

**Comment by brianteeman** [comment]
obvious fix - should not have been changed in the first place

**Comment by davidnguyen-joomlashine** [comment]
The status is the drop-down
download
 type now

**Comment by joomlacorner** [comment]
@brianteeman @marcodings  if we can't changed xml for support this template. May be we need override xml feature from Core feature.?   or need to build plugin to work like this plugin ?  http://icueproject.com/products/override-xml-forms   
What's do you think?

**Comment by brianteeman** [comment]
@joomlacorner Krit it is not that simple. It is not just the xml files that are being changed that cannot be overridden

**Pull request merged**
