### PR TITLE
Fixed issue #51, change Joomla! logo glossy to flat colored

### PR DESCRIPTION
**Pull request by ahamed**
Pull Request for Issue #51, glossy to flat Joomla! logo.

### Expected result
Flat colored logo.

### Actual result
Glossy colored logo.

### CODE REVIEW

**Comment by brianteeman** [comment]
LGTM - do we still need to ship the glossy logo?

**Comment by brianteeman** [comment]
The ci failures do look valid issues

**Comment by ahamed** [comment]
> LGTM - do we still need to ship the glossy logo?

@sahidhossen did we use the glossy Joomla! logo anywhere else?

**Comment by sahidhossen** [comment]
> > LGTM - do we still need to ship the glossy logo?
> 
> @sahidhossen did we use the glossy Joomla! logo anywhere else?

No I didn't use anywhere else.

**Comment by davidnguyen-joomlashine** [comment]
I checked and this fixs correctly the issue
Screenshot (1)

**Comment by ahamed** [comment]
Thank you @davidnguyen-joomlashine.

**Pull request merged**
