### PR TITLE
Add dashboard modules at coreExtensions array.

### PR DESCRIPTION
**Pull request by ahamed**
Pull Request for Issue #143 .

### Summary of Changes
Add the newly added dashboard modules into the `$coreExtensions` array in `ExtensionHelper.php` file.

### CODE REVIEW

**Comment by brianteeman** [comment]
lgtm

**Comment by kawshar** [comment]
Looks alright (Y)

**Comment by joomlacorner** [comment]
where the screen will be effected from this?   
after patch.
I try click add module to dashboard but don't see new modules name add to the list.
Screen Shot 2562-12-06 at 17 04 03

**Comment by kawshar** [comment]
> where the screen will be effected from this?
> after patch.
> I try click add module to dashboard but don't see new modules name add to the list.
> Screen Shot 2562-12-06 at 17 04 03

You need to discover and install those modules.

**Comment by joomlacorner** [comment]
@kawshar   ok, Patch worked. found modules in list.
Screen Shot 2562-12-06 at 17 33 55

**Pull request merged**
